on:
  - push
  - pull_request
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm install
      - run: npm install --no-save c8
      - run: npx c8 npm test
      - run: npx c8 report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v2
  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run build
      - run: npm publish
        if: contains(github.ref, 'tags/v')
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
